### PR TITLE
Modify the code to capture the upper 4 bits of the *FX 151,230 and us…

### PR DESCRIPTION
**Pull request by fordp2002**
…e them as options for CoPro's

Use the upper 4 bits on the 32016 to select the RAM size
Uncomment the #define RAM_SIZE to revert to a Hard Coded RAM Size

### CODE REVIEW

**Comment by fordp2002** [comment]
No need to use my code but it would be good to be able to set the RAM size on the 32016 as both 1MB and 4MB models were out there.

**Comment by hoglet67** [comment]
I'm conscious that this did not get included in Boa, mostly because we had work in progress to enable a more general model for co processor configuration that allows up to 256 parameters.
- *FX 151,226,<param address> (defaults to zero)
- *FX 151,228,<param data>

So far we have defined:
- param address 00 = Set Speed, data = value in MHz

We could add:
- param address 01 = Set Memory Size

Simon, would you still like to see the ability to configure the 32016 memory size included?

We need to decide the units; I expect MB (1MB-256MB) would be too course.

What about units of 128KB (128KB to 32MB)? But then 32MB is too small for the native ARM Co Pro.  Unless we allowed the value 0 to mean "max supported".

The use case for this is mostly accurately emulation existing hardware configurations, e.g. to test if there is sufficient memory to run some specific program.

**Comment by fordp2002** [comment]
Hi I would love to see the memory size feature in there. 128KB is the correct quantum for the 32016. The point about this feature is that there were genuinely 32016 CoPro's with various sizes. I think most of the Wedge ones would have been 1MB and the ABC version was probably always 4MB.

If it were me I would make the quantum specific to the CoPro.

Let me know if you want me to submit another patch against the current head/ develop.

Cheers.

**Comment by BigEd** [comment]
I think we'll need 0 to be the default value for each copro. Perhaps 255 could be the max sane value?
Does it make sense to have a non linear scale which accommodates most cases?
0 - default
1 - 64k
up to
63 - 63*64k
64 - 64*64k = 32*128k = 4MByte
65 - 33*128k
up to
127 - 95 * 128k
128 - 96 * 128k = 12MByte
129 - 13MByte
up to
244 - 128MByte
245..254 reserved?
255 - max sensible amount according to CPU and Pi

Another possibility is to make byte 1 the number of k up to 255k, and byte 2 a more significant byte, taking us to 64MByte, and byte 3 if needed the next byte up taking us to the capacity of the Pi.  To configure 640kB, byte 1 is 128 and byte 2 is 2.

**Comment by fordp2002** [comment]
Here's what I did for the 32016:

#ifndef RAM_SIZE
   switch ((co_options >> 4) & 0x0F)
   {
      default:
      case 0: RAM_SIZE = MEG1; break;
      case 1: RAM_SIZE = K128; break;
      case 2: RAM_SIZE = K256; break;
      case 3: RAM_SIZE = K512; break;
      case 4: RAM_SIZE = K640; break;
      case 5: RAM_SIZE = MEG2; break;
      case 6: RAM_SIZE = MEG4; break;
      case 7: RAM_SIZE = MEG8; break;
      case 8: RAM_SIZE = MEG15; break;
   }
#endif
}

I could only think of 9 logical values for the size!

The ninth one is just a bit of fun to go beyond 8MB ;)

**Comment by dp111** [comment]
Just thinking here now real thought.

0 should be default for cpu

bit 7 =0 step size 64K
bit 7 =1 step size 8Mbytes
bits 6-0 memory size times either 64K or 8Mbytes

**Comment by hoglet67** [comment]
+1 for Dominic's suggestion

**Comment by BigEd** [comment]
Me too (already gave it a thumbs-up but that's not a very clear communication)

**Comment by fordp2002** [comment]
Covers the needs for the 32016 so fine by me.

**Comment by BigEd** [comment]
The new mechanism is working nicely in cobra-dev, so we can close this issue/pull req when Cobra ships. Which should be fairly soon!

**Comment by hoglet67** [comment]
Closing, as this was implemented in a slightly different way, usinf *FX 151,226 and *FX 151,228.

**Pull request closed without merging**
