### PR TITLE
Added 6502 memory co-processor list code at &2000

### PR DESCRIPTION
**Pull request by mincebert**
This adds another program into the 6502 memory space - a short machine language program at &2000 that just displays a list of the available coprocessors.

It draws on the emulator-names array in tube-client.c but I had to separate that out to get to it from programs.c as well.  It dynamically constructs the text to avoid having to maintain it separately.

I'm not sure if you think it's a good idea but it saves me having to keep a list to hand, although the Fer-de-Lance update made the numbers much easier to remember - thanks!

Excuse my C - I haven’t written any for about 15 years!

### CODE REVIEW

**Comment by BigEd** [comment]
(@hoglet67 did you see this?)

**Comment by hoglet67** [comment]
I'll merge this when I next do some work on PiTubeDirecct.

**Comment by beebmaster** [comment]
Could this information also be included in the Native ARM, maybe as additional help text in the Native ARM ROM, called up with *HELP TUBELIST or similar?

**Comment by hoglet67** [comment]
Yes, I can find a way to do this.

I'll probably just add a * command.

**Comment by hoglet67** [comment]
#83

**Comment by hoglet67** [comment]
Closing as this is now merged into gecko-dev

**Pull request closed without merging**
